In [1]:
import cv2

In [ ]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

img = cv2.imread("modi.jpg")
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces=face_cascade.detectMultiScale(gray_img,
                                    scaleFactor=1.055,
                                    minNeighbors=5,
                                   )

for x,y,w,h in faces:
    img=cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)

print(faces)
print(type(faces))

resized = cv2.resize(img,(int(img.shape[1]/3),int(img.shape[0]/3)))
cv2.imshow("Resized", resized)
cv2.imwrite("detected_modi.jpg",resized)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[635 454 104 104]
 [692  64  60  60]
 [824  66  61  61]
 [489  56  79  79]
 [600  76  78  78]]
<class 'numpy.ndarray'>
